### ISSUE TITLE
eid现在好像获取不到了

### ISSUE THREAD

**Issue by SunJun8** [BlackWatch0/JDspyder#26]

**Comment by SunJun8** [comment]
chrome可以，edge不行

**Comment by adaaaaaa** [comment]
> chrome可以，edge不行

火狐可以吗？我火狐好像不行。。。呜呜呜。。。

**Comment by SunJun8** [comment]
> > chrome可以，edge不行
> 
> 火狐可以吗？我火狐好像不行。。。呜呜呜。。。

没用过Firefox，不行就装个chrome
