### ISSUE TITLE
大佬 开个tg群吧   

### ISSUE THREAD

**Issue by yanghonghao6789** [BlackWatch0/JDspyder#6]
大佬 开个tg群吧

**Comment by yanghonghao6789** [comment]
![image](https://user-images.githubusercontent.com/73630536/208250630-d043fa36-f5b0-40d7-97c7-e8ec85b6d045.png)
大佬  我把脚本放到青龙里  添加了一个依赖 可以运行了。
但是在青龙里运行有个问题 怎么应对 预约 抢购的选择啊  1 、2   没有地方输  可以写进去  比如根据时间判断 未到预约时间 就默认执行预约操作  过了预约 未到抢购 执行抢购操作    
还有那个扫码登录 能不能改用cookie登录  这样就不需要每次豆扫码了  青龙里解决这两步就可以在容器内运行了 大大方便了使用。

**Comment by renhuiyong** [comment]
已测试不能用
1.预约 到达预约时间不会进行购买
2.抢购 到达抢购时间输出： - INFO: 抢购链接获取失败，稍后自动重试
