### ISSUE TITLE
如果商品是只能手机抢够的，就无法抢购。

### ISSUE THREAD

**Issue by flyyoun** [BlackWatch0/JDspyder#9]
如下图，有这种手机扫码才能购买的商品都不能抢购。原程序是抢茅台的，但是茅台也是这种情况，也就是说程序只能抢一些不太重要的东西了，效用力下降。

![image](https://user-images.githubusercontent.com/31716296/208818573-d36bbd1c-e162-4db0-9fc8-5cd0963125ef.png)

**Comment by samulenzz** [comment]
有不需要手机抢的抗原，试试那些吧兄弟
手机端的需要重新抓包，现在抢不到下不了单，也改不了程序

**Comment by flyyoun** [comment]
> 有不需要手机抢的抗原，试试那些吧兄弟 手机端的需要重新抓包，现在抢不到下不了单，也改不了程序

好的非常感谢！
